### ISSUE TITLE
Link to "Hugging Face" is misspelled and leads to wrong domain

### ISSUE THREAD

**Issue by jeroenheijmans** [vercel-labs/ai#100]
The homepage at https://sdk.vercel.ai/docs has a link to `https://` + `hugginface.co/` which is missing a `g` in there. The domain it does link to seems to be grabbed by a party that's doing all sorts of non-AI-stuff, I'm unsure how legit it even is what they have on their site.

I presume the correct link should be `https://huggingface.co/`, right?

See these [search results in this repo](https://github.com/search?q=repo%3Avercel-labs%2Fai%20hugginface&type=code) for the files to be changed, at the moment:

https://github.com/vercel-labs/ai/blob/4315d174a897adfae4461bf5315ff68bd54e2f93/docs/pages/docs/guides.mdx?plain=1#L7

and

https://github.com/vercel-labs/ai/blob/4315d174a897adfae4461bf5315ff68bd54e2f93/docs/pages/docs/index.mdx?plain=1#L120

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This is a typo and broken external link in the documentation, requiring only a documentation content correction.

### Evidence
- The documentation links to the misspelled domain `hugginface.co`.
- The issue identifies the correct Hugging Face URL as `https://huggingface.co/` and points to two documentation files needing correction.
