### ISSUE TITLE
README file for npm

### ISSUE THREAD

**Issue by e-roy** [vercel-labs/ai#106]
Visiting the [npm package page](https://www.npmjs.com/package/ai) there is no README file.  

Would be nice to see here :)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This requests adding package documentation to the npm page and does not describe a product behavior failure.

### Evidence
- The npm package page for `ai` does not display a README.
- The reporter asks for README content to be made available on npm.
