### ISSUE TITLE
No matching version for "ai" that matches "2.1.1"

### ISSUE THREAD

**Issue by JackHowa** [vercel-labs/ai#110]
Looking forward to using this starter and the integrations. Appreciate the work here. Seeing an issue after trying to deploy the next.js openai starter: 

```
Vercel CLI 30.2.1
--
09:27:41.741 | Installing dependencies...
09:27:41.992 | yarn install v1.22.17
09:27:42.011 | info No lockfile found.
09:27:42.015 | [1/4] Resolving packages...
09:27:44.822 | error Couldn't find any versions for "ai" that matches "2.1.1"
09:27:44.822 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
09:27:44.842 | Error: Command "yarn install" exited with 1
09:27:45.232 | BUILD_UTILS_SPAWN_1: Command "yarn install" exited with 1
```

Looks like the latest release is 2.1.0.

https://github.com/vercel-labs/ai/releases/tag/ai%402.1.0
<img width="1225" alt="See latest release is 2.1.0" src="https://github.com/vercel-labs/ai/assets/5950956/1d2306e1-8158-4730-bcb0-d71fefc69dd3">

Also this seems like it's a similar problem as #82

**Comment by FelixWaweru** [comment]
I'm also getting the same error

Maybe the automated build for version 2.1.1 didn't deploy the package?

**Comment by bcarsley** [comment]
Yeah just like to agree here -- tried both npm and pnpm, various different ways of building, same error as show above. I will manually clone, change the version, and see if that works -- seems like an easy enough fix

**Comment by bcarsley** [comment]
> Yeah just like to agree here -- tried both npm and pnpm, various different ways of building, same error as show above. I will manually clone, change the version, and see if that works -- seems like an easy enough fix

Update: yes, changing to 2.1.0 does in fact allow it to build and start the server on localhost (pnpm install => pnpm dev) ... BUT there are some issues with the class StreamingTextResponse, which could be a module versioning problem -- seems like this build may actually be dependent on the release of 2.1.1? see tracebacks below, I didn't change anything else about the build other than the version of the ai module (and as you can see even in 2.1.0 StreamingTextResponse seems to be defined as a constructor, making the traceback i got kinda curious)
<img width="1409" alt="Screenshot 2023-06-16 at 11 22 21 AM" src="https://github.com/vercel-labs/ai/assets/119977492/34c16a90-b2a4-4fb0-92ec-b98b8ec419e8">
<img width="748" alt="Screenshot 2023-06-16 at 11 22 47 AM" src="https://github.com/vercel-labs/ai/assets/119977492/e2904a65-b31a-4880-ab54-7b67b0092b4f">

**Comment by ashrielbrian** [comment]
@bcarsley I got around it by simply creating the `Response` class on my own, since `StreamingTextResponse` is just a wrapper around it:

```
return new Response(stream, {
        status: 200,
        headers: {
            "Content-Type": "text/plain; charset=utf-8"
        }
    })
// return new StreamingTextResponse(stream)
```

**Comment by shuding** [comment]
Thanks for the feedback! Can you try 2.1.2? It should have the problems fixed.

**Comment by JackHowa** [comment]
ok thanks @shuding -- installing as expected!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The starter's existing dependency configuration referenced an unavailable package version and could not build as provided. The failure was acknowledged and fixed in a subsequent release, making this a concrete bug.

### Evidence
- The Next.js OpenAI starter depended on unpublished `ai@2.1.1`, causing dependency installation and deployment to fail across Yarn, npm, and pnpm.
- Downgrading to 2.1.0 allowed installation but produced a runtime `StreamingTextResponse is not a constructor` error.
- A maintainer stated that 2.1.2 fixed the problems, and the reporter confirmed installation then worked.
