### ISSUE TITLE
next-openai example out of the box fails to work

### ISSUE THREAD

**Issue by ZiggStardust** [vercel-labs/ai#117]
Steps to reproduce 

1. `npx create-next-app --example https://github.com/vercel-labs/ai/tree/main/examples/next-openai next-openai-app`
2. npm i
3. create .env file with OPENAI_API_KEY with a valid open api key 
4. type in input box - error returned from api request 

<img width="891" alt="Screenshot 2023-06-16 at 14 23 58" src="https://github.com/vercel-labs/ai/assets/5075794/98fa258d-8566-4b88-9e44-4867935277e3">
<img width="878" alt="Screenshot 2023-06-16 at 14 23 55" src="https://github.com/vercel-labs/ai/assets/5075794/627e2f2b-b90e-4ab8-86a0-d0c34bcde69f">

**Comment by MaxLeiter** [comment]
It seems to work for me: 
<img width="926" alt="CleanShot 2023-06-16 at 13 31 25@2x" src="https://github.com/vercel-labs/ai/assets/8675906/2e73892f-58b9-42cc-b33e-03ebece7bc68">


Can you share any more details on the error, like what's printed to your server console?

**Comment by dkasper** [comment]
I'm seeing the same `{"props":{"pageProps":{"statusCode":500}},"page":"/_error","query":{"__NEXT_PAGE":"/api/chat"},"buildId":"development","isFallback":false,"err":{"name":"Error","source":"edge-server","message":"Failed to convert the response to stream. Received status code: 404.","stack":"Error: Failed to convert the response to stream. Received status code: 404.\n    at AIStream (webpack-internal:///(sc_server)/./node_modules/.pnpm/ai@2.1.2_react@18.2.0_svelte@3.59.1_vue@3.3.4/node_modules/ai/dist/index.mjs:116:15)\n    at OpenAIStream (webpack-internal:///(sc_server)/./node_modules/.pnpm/ai@2.1.2_react@18.2.0_svelte@3.59.1_vue@3.3.4/node_modules/ai/dist/index.mjs:136:12)\n    at POST (webpack-internal:///(sc_server)/./src/app/api/chat/route.ts:27:68)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:229:37)"},"gip":true,"scriptLoader":[]}`

**Comment by shuding** [comment]
There should be an error on the console which helps you debug this. Also might be helpful to directly check the response from OpenAI.

**Comment by ZiggStardust** [comment]
the model is set to gpt-3.5-turbo ...

**Comment by ZiggStardust** [comment]
<img width="871" alt="Screenshot 2023-06-16 at 17 54 48" src="https://github.com/vercel-labs/ai/assets/5075794/cc62546b-f5f1-4091-aaa0-dbd9302f6b84">

**Comment by dkasper** [comment]
429 error sounds like you're being rate limited by openai

**Comment by ZiggStardust** [comment]
hmm ok i'll try another account

**Comment by AdrianFerrer1** [comment]
Getting the same error even on a fresh openai account, tried model text-davinci-003 and it is the same

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The failure was traced to an external OpenAI account/rate-limit condition rather than a defect in the AI SDK or example, making this primarily a support issue.

### Evidence
- The example returned a 500 response because the underlying OpenAI request returned HTTP 429.
- A maintainer reproduced the example successfully.
- The discussion concluded the reporter was likely rate-limited by OpenAI and would try another account.
