### ISSUE TITLE
Question: when will OpenAI's gpt-4.0 be supported?

### ISSUE THREAD

**Issue by lionkeng** [vercel-labs/ai#129]
Will there be OpenAI support for gpt-4.0 and if so what is timeline?

**Comment by evgenyrodionov** [comment]
[❓](https://github.com/vercel-labs/ai/blob/main/packages/core/README.md?plain=1#L37)

**Comment by Itsnotaka** [comment]
It's already supported...??

**Comment by evgenyrodionov** [comment]
yes, chef

**Comment by shuding** [comment]
It’s already supported by this library, you can also try out the playground.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a support question resolved by pointing out existing functionality, not a report of broken behavior or a request requiring a product change.

### Evidence
- The issue asks whether GPT-4 support exists and requests a timeline.
- Multiple comments clarify that GPT-4 was already supported by the library.
