### ISSUE TITLE
Allow changing `body` with `useCompletion`

### ISSUE THREAD

**Issue by mmurto** [vercel-labs/ai#131]
I've got an endpoint that takes custom additional data - it would make using `useCompletion` a lot easier in many situations if it exposed `setBody` or something similar.

**Comment by Itsnotaka** [comment]
Check the docs! Use the body property on useCompletion function 
[Doc](https://sdk.vercel.ai/docs/api-reference/use-completion)

**Comment by mmurto** [comment]
> Check the docs! Use the body property on useCompletion function

I mean to change the body property after instantiating `useCompletion`, or adding body to the `complete` call. This is basically what I want to achieve (or `setBody` before calling `complete`), with `response` being the additional data.

```ts
const { complete } = useCompletion();

api.edge.search.context.useMutation({
  onSuccess: (response) => {
    complete(query, response);
  },
});
```

**Comment by shuding** [comment]
Good call - ideally all methods that trigger a request should accept an extra optional option, that can contain custom body and headers.

**Comment by bioshazard** [comment]
I just adopted this library today. I am utilizing `useChat` and have an issue where I am using a middleware with an expiring token. So I need to update the headers.authorization every time I make a call. Gonna look at a PR if no one else is already known to be working on it. I think generic overriding is the ideal indeed.

**Comment by bioshazard** [comment]
If there was an additional `setMetadata` function added to the returned helpers object we could set headers for auth and body as needed synchronously before any call.

Like...

```
const setMetadata = ({ headers, body }) => {
    if(headers) {
      extraMetadataRef.current = {
        ...extraMetadataRef.current,
        headers
      }
    }
    if(body) {
      extraMetadataRef.current = {
        ...extraMetadataRef.current,
        body
      }
    }
```

I think I see how to add it but I am not sure how to develop in a published NPM library... Will try to study some to wrap my head around how to maybe contribute this in a PR. Any tips are welcome.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests an API expansion that allows per-request customization of body and headers, so it is a new capability rather than a defect.

### Evidence
- The reporter wants to change the request body after `useCompletion` is instantiated, either through `setBody` or an option passed to `complete`.
- The maintainer agrees that request-triggering methods should accept optional custom body and headers.
- No existing documented behavior is described as broken.
