### ISSUE TITLE
Strange question marks �� in cyrillic symbols

### ISSUE THREAD

**Issue by TimPchelintsev** [vercel-labs/ai#155]
Hi! Thanks for great lib. Screenshot from https://chat.vercel.ai:
<img width="763" alt="Screenshot 2023-06-19 at 07 38 59" src="https://github.com/vercel-labs/ai/assets/3499434/363c0d49-b632-40ec-8bc7-257d0109bbaa">

It seems like an encoding issue, and it seems to appear only on Vercel deployment.

**Comment by jridgewell** [comment]
This is almost certainly because we're not using the `stream` option on our `TextDecoder`s, so it's processing a split UTF octet and treating it as invalid text.

**Comment by TimPchelintsev** [comment]
Hi guys thanks for quick response but is seems issue is still present. Question marks still appear on https://chat.vercel.ai and in my product even after upgrade to new version with ```stream: true``` fix.
Recent screenshot from https://chat.verce.ai:
<img width="730" alt="Screenshot 2023-06-23 at 10 43 30" src="https://github.com/vercel-labs/ai/assets/3499434/e0f0a6f3-48f1-42b0-afb7-38ab81ce10a5">

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete failure in existing streamed text handling: valid Cyrillic characters are intermittently decoded as replacement characters, and the attempted fix did not fully resolve it.

### Evidence
- Streamed Cyrillic output contains Unicode replacement characters (��), indicating corrupted UTF-8 decoding.
- A commenter attributes the failure to TextDecoder processing split UTF-8 octets without correct streaming behavior.
- The reporter confirms the corruption remains in both chat.vercel.ai and their product after upgrading to a version containing the proposed `stream: true` fix.
