### ISSUE TITLE
Unable to fetch server using useChat hook

### ISSUE THREAD

**Issue by rodneymbrown1** [vercel-labs/ai#157]
I tried to set up the useChat hook in my Next.js application to fetch data from the server, but I'm encountering difficulties in fetching the server.  I have verified the correctness of the endpoint URL and the presence of the route.ts file.  I suspect there might be an issue with the implementation of either the hook or the API route. Any assistance in troubleshooting this problem would be greatly appreciated.

import { useChat } from 'ai/react';

client side 
```
export default function  () {...
 const { messages, input, handleInputChange, handleSubmit } = useChat({api:'pages/api/chat/route.ts'});

 <div className="max-w-sm mx-auto" id="input-container">
                {messages.map(m => (<div key={m.id}> {m.role === 'user' ? 'User: ' : 'AI: '}
                  {m.content}</div>))}

                <form onSubmit={handleSubmit}>
                  
                  <input type="text" value={input} onChange={handleInputChange}
                    className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500" placeholder="Ask a question..." />

                  <button type="submit"
                    className="mt-4 w-full px-4 py-2 bg-indigo-500 text-white font-bold rounded-md hover:bg-indigo-600 focus:outline-none focus:bg-indigo-600">Ask</button>
                </form>
              </div>
```

Server side...
"
import { Configuration, OpenAIApi } from 'openai-edge';
import { OpenAIStream, StreamingTextResponse } from 'ai';

// Create an OpenAI API client (that's edge friendly!)
const config = new Configuration({
  apiKey: process.env.OPENAI_API_KEY
})
const openai = new OpenAIApi(config)
 
// IMPORTANT! Set the runtime to edge
export const runtime = 'edge'
 
```
export async function POST(req: Request) {
  // Extract the `messages` from the body of the request
  const { messages } = await req.json()
 
  // Ask OpenAI for a streaming chat completion given the prompt
  const response = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo',
    stream: true,
    messages
  })
  // Convert the response into a friendly text-stream
  const stream = OpenAIStream(response)
  // Respond with the stream
  return new StreamingTextResponse(stream)
}
```

**Comment by CarlosZiegler** [comment]
I think the route is incorrect, you will call : '/api/chat/route.ts' inetad of 'pages/api/chat/route.ts'. 
like:
<img width="641" alt="image" src="https://github.com/vercel-labs/ai/assets/38855507/b4dc9be1-6c98-4726-a1a6-fc28bfd8ddad">

reference: https://github.com/CarlosZiegler/next-ai/blob/main/app/pdf/page.tsx

**Comment by shuding** [comment]
Hi! It’s incorrect to specify the API **file name** here: `useChat({ api: 'pages/api/chat/route.ts' })`. You’ll need to pass the URL and in this case it should be just `'/api/chat'`.

**Comment by rodneymbrown1** [comment]
Thankyou for the correction.  Here is what I am seeing in the browser at the instance before the onclick fetch via 

```
console.log(JSON.stringify
("messages: "+JSON.stringify(messages)+
" input: "+JSON.stringify(input)+
" handleInputChange: "+JSON.stringify(handleInputChange)+
" handleSubmit: "+JSON.stringify(handleSubmit)));
```
`"messages: [] input: \"hello chatbot\" handleInputChange: undefined handleSubmit: undefined"`

I am not sure if handleInputCHange, and handleSubmit should be undefined at this point.

Once the onclick method is executed using **/api/chat**  as the endpoint, I can see that the 
404 URL is 
www.example.com/api/chat

Im not sure if this is proper github etiquette, but here is the replit project if you want to take a gander.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a support/debugging request caused by an incorrect API path and possibly missing or misplaced Next.js routing. No concrete AI SDK defect is established.

### Evidence
- The original configuration passes a source file path (`pages/api/chat/route.ts`) instead of an API URL to `useChat`.
- A maintainer clarified that the correct value is `'/api/chat'`.
- The follow-up reports a 404 at `/api/chat`, indicating an application route/setup problem rather than a demonstrated SDK failure.
- The issue is framed as a request for troubleshooting assistance.
