### ISSUE TITLE
Adding chains from Langchain to work with streaming/calling

### ISSUE THREAD

**Issue by ErwinAI** [vercel-labs/ai#169]
First of all, great job on this npm package! It's really helping me a lot with my first steps into AI dev.

I've been trying to add a chain from LangChain working, but unfortunately I'm not able to figure out how to do this.
My desired flow is the following: 1) obtain relevant documents from Pinecone 2) Add these with [MapReduceDocumentsChain](https://js.langchain.com/docs/modules/chains/index_related_chains/document_qa) 3) query OpenAI with those documents as embeds.

This is the code I currently have. It uses the Nuxt+Langchain example as boilerplate. The current outcome is two separate calls with two responses. I've also tried to `.apply()` the chain rather than `.call()` but the result is the same. I want to be able to chain the LangChainStream to the streamToResponse, essentially.

Any help or pointers would be much appreciated!

```
import { LangChainStream, streamToResponse, Message } from 'ai'
import { CallbackManager } from 'langchain/callbacks'
import { ChatOpenAI } from 'langchain/chat_models/openai'
import { AIChatMessage, HumanChatMessage } from 'langchain/schema'
import { PineconeClient } from '@pinecone-database/pinecone'
import { PineconeStore } from 'langchain/vectorstores/pinecone'
import { OpenAIEmbeddings } from 'langchain/embeddings/openai'
import { loadQAMapReduceChain } from 'langchain/chains'
export const runtime = 'edge'
export default defineEventHandler(async (event: any) => {
  // Extract the `prompt` from the body of the request
  const { messages } = await readBody(event)

  const { stream, handlers } = LangChainStream()

  const llm = new ChatOpenAI({
    modelName: 'gpt-3.5-turbo-0613',
    temperature: 0.5,
    openAIApiKey: process.env.OPENAI_API_KEY,
    streaming: true,
    callbackManager: CallbackManager.fromHandlers(handlers)
  })

  const lastMessage = messages[messages.length - 1]
  let pineconeResult
  if (lastMessage.role === 'user') {
    const client = new PineconeClient()
    await client.init({
      apiKey: process.env.PINECONE_API_KEY ?? '',
      environment: process.env.PINECONE_ENVIRONMENT ?? ''
    })
    const pineconeIndex = client.Index(process.env.PINECONE_INDEX ?? '')
    const vectorStore = await PineconeStore.fromExistingIndex(new OpenAIEmbeddings(), { pineconeIndex })

    // Search the vector DB
    pineconeResult = await vectorStore.similaritySearch(lastMessage.content, 1)

    // the way to use loadQAMapReduceChain. The result is a call.
    const chain = loadQAMapReduceChain(llm)
    await chain.call({
      input_documents: pineconeResult,
      question: lastMessage.content
    })
  }

  // call as shown in the 'ai' package documentation/examples
  llm
    .call(
      (messages as Message[]).map(message =>
        message.role === 'user'
          ? new HumanChatMessage(message.content)
          : new AIChatMessage(message.content)
      )
    )
    // eslint-disable-next-line no-console
    .catch(console.error)

  return streamToResponse(stream, event.node.res)
})
```

**Comment by jaredpalmer** [comment]
@timqian is correct. Closing for now.

**Comment by ErwinAI** [comment]
Thank you for the response and sample @timqian! Using `VectorDBQAChain` is an alternative way to chain Pinecone/embed but yields the same results 👍

The problem I'm facing with this approach is that we don't use `ai` 's .call() method and so we don't actually get any streaming. It's a long wait and then the answer just pops out of nowhere (cc @jaredpalmer).

**Comment by anhhtca** [comment]
Thanks for your example code ! I'm very new to the AI.
I don't understand the code above yet:

> ```js
> const pineconeIndex = client.Index(process.env.PINECONE_INDEX || "");
> 
>   const vectorStore = await PineconeStore.fromExistingIndex(
>     new OpenAIEmbeddings({ openAIApiKey: process.env.OPENAI_API_KEY }),
>     { pineconeIndex }
>   );
> ```

I have a text file for QA. How can I import/insert or add it to Pinecone? So what is `process.env.PINECONE_INDEX`. Do you have an already content put in `.env` ?

Thanks in advanced !

**Comment by anhhtca** [comment]
My `vectorStore` (MemoryVectorStore) contains Vietnamese text. Why does ChatGPT return English content that is translated from the Vietnamese content?

**Comment by jaocfilho** [comment]
@timqian May I ask you why did you use `VectorDBQAChain` instead of `ConversationalRetrievalQAChain`?

**Comment by brerdem** [comment]
I also want to use `useChat` hook on UI and it seems it's only available with `ChatOpenAI ` model. How can I combine chat models with some chain like `ConversationalRetrievalQAChain ` ?  I'd really appreciate a quick example.

**Comment by jaocfilho** [comment]
@brerdem take a look at this [issue](https://github.com/vercel-labs/ai/issues/246#issue-1779887448)

**Comment by timqian** [comment]
> @timqian May I ask you why did you use VectorDBQAChain instead of ConversationalRetrievalQAChain?
@jaocfilho @brerdem I am using VectorDBQAChain, as I don't need to restore the chat history, haven't tried ConversationalRetrievalQAChain

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily an integration/support discussion seeking implementation guidance, not a confirmed failure of documented AI SDK behavior or a direct request to change documentation or examples.

### Evidence
- The reporter asks for help combining LangChain chains, Pinecone retrieval, and AI SDK streaming.
- A commenter provides a working integration example, and a maintainer agrees and closes the issue.
- Follow-up comments continue as implementation questions about streaming and choosing LangChain chain types, without confirmation of an AI SDK defect.
