### ISSUE TITLE
Feedback for “Getting Started”

### ISSUE THREAD

**Issue by sahildkun** [vercel-labs/ai#171]
actually i tried the new vercel sdk and followed the docs but i am able to generate only two text quotes instead of 3 slogans by using the useCompletion() hook 
even though the prompt is for 3 slogans

**Comment by jaredpalmer** [comment]
can you share your code?

**Comment by sahildkun** [comment]
app/page.tsx

`'use client'
 
import { useCompletion } from 'ai/react';
 
export default function SloganGenerator() {
  const { completion, input, handleInputChange, handleSubmit } = useCompletion();
 
  return (
    <div className="mx-auto w-full max-w-md py-24 flex flex-col stretch">
      <form onSubmit={handleSubmit}>
        <input
          className="fixed w-full max-w-md bottom-0 border border-gray-300 rounded mb-8 shadow-xl p-2"
          value={input}
          placeholder="Describe your business..."
          onChange={handleInputChange}
        />
      </form>
      <div className="whitespace-pre-wrap my-6">{completion}</div>
    </div>
  );
}`


app/api/completion/route.ts

`import { Configuration, OpenAIApi } from 'openai-edge';
import { OpenAIStream, StreamingTextResponse } from 'ai';
 
// Create an OpenAI API client (that's edge friendly!)
const config = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});
const openai = new OpenAIApi(config);
 
// IMPORTANT! Set the runtime to edge
export const runtime = 'edge';
 
export async function POST(req: Request) {
  const { prompt } = await req.json();
 
  // Ask OpenAI for a streaming completion given the prompt
  const response = await openai.createCompletion({
    model: 'text-davinci-003',
    stream: true,
    temperature: 0.6,
    prompt: `Create three slogans for a business with unique features.
 
Business: Bookstore with cats
Slogans: "Purr-fect Pages", "Books and Whiskers", "Novels and Nuzzles"
Business: Gym with rock climbing
Slogans: "Peak Performance", "Reach New Heights", "Climb Your Way Fit"
Business: ${prompt}
Slogans:`,
  });
  // Convert the response into a friendly text-stream
  const stream = OpenAIStream(response);
  // Respond with the stream
  return new StreamingTextResponse(stream);
}`

**Comment by sahildkun** [comment]
[https://github.com/sahildkun/vercel-ai-sdk](url)

this is the link of the repository , it has the same code as guided in getting started page .

**Comment by MaxLeiter** [comment]
I recommend experimenting with different models and prompts. From reviewing your repository the problem isn’t with the SDK.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a prompt/model output variability support issue rather than a demonstrated failure in the AI SDK, documentation, or example code.

### Evidence
- The reporter received two slogans instead of the three requested by the prompt while using `useCompletion()`.
- After reviewing the linked reproduction, a maintainer stated that the problem was not with the SDK and recommended trying different models and prompts.
