### ISSUE TITLE
Pinecone init error

### ISSUE THREAD

**Issue by riccardolinares** [vercel-labs/ai#186]
Hi, 

I am creating an API Route to create a Pinecone Index before calling the handleSubmit function of useChat(). 
Everything works well on localhost, but when deploying to production on Vercel the Pinecone namespace is not created correctly. 

Moreover I am getting this warning, which I don't know if it is related to the error:
![image](https://github.com/vercel-labs/ai/assets/10235116/f8388e5b-9c7f-44a7-a4a3-4d3440826201)

The error is caused by the pinecone init:
```
    await pineconeClient.init({
      apiKey: process.env.PINECONE_API_KEY as string,
      environment: process.env.PINECONE_ENVIRONMENT as string,
    });
```

This is the entire code of the **/api/upload** :
```
export async function POST(req: NextRequest) {
  try {
    const data = await req.formData();
    const files = data.getAll("files") as File[];
    const path = data.get("path") as string;

    console.log("files", files, "path", path);

    if (!files) {
      return NextResponse.json(
        { success: false, message: "No file provided" },
        { status: 400 }
      );
    }

    // init pinecone client
    const pineconeClient = new PineconeClient();

    await pineconeClient.init({
      apiKey: process.env.PINECONE_API_KEY as string,
      environment: process.env.PINECONE_ENVIRONMENT as string,
    });
    const pineconeIndex = pineconeClient.Index(
      process.env.PINECONE_INDEX as string
    );

    // init splitter
    const splitter = new RecursiveCharacterTextSplitter({
      chunkSize: 1024,
      chunkOverlap: 128,
    });

    // // init pinecone store
    const pineconeStore = new PineconeStore(embeddings, {
      pineconeIndex: pineconeIndex,
      namespace: path,
    });

    files.map(async (file: File) => {
      // load the document
      const loader = new PDFLoader(file as Blob, {
        splitPages: false,
      });
      const loadedDocs = await loader.load();

      const splittedDocs = await splitter.splitDocuments(loadedDocs);
      await pineconeStore.addDocuments(splittedDocs);
    });

    return NextResponse.json({
      success: true,
      userId: path,
      pineconeId: path,
    });
  } catch (e) {
    console.log(e);
    return NextResponse.json(
      { success: false, message: "Error" },
      { status: 500 }
    );
  }
}
```

Note: I am using Next 13 with App Route.

**Comment by riccardolinares** [comment]
ok, that was easier than expected: I was submitting the response without having waited for all the files to be uploaded to Pinecone.

Solution:

```
**const uploadedFiles =** files.map(async (file: File) => {
      // load the document
      const loader = new PDFLoader(file as Blob, {
        splitPages: false,
      });
      const loadedDocs = await loader.load();

      const splittedDocs = await splitter.splitDocuments(loadedDocs);
      await pineconeStore.addDocuments(splittedDocs);
    });

  **await Promise.all(uploadedFiles);**
```


Problem solved 😄

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a resolved implementation/support issue caused by unawaited asynchronous work in the reporter's code, not an AI SDK bug, documentation request, example change, or feature request.

### Evidence
- The production failure was caused by returning the API response before the asynchronous Pinecone uploads completed.
- The reporter resolved it by awaiting `Promise.all(uploadedFiles)` and explicitly stated, "Problem solved."
- No broken AI SDK behavior or requested repository change was identified.
