### ISSUE TITLE
Add `setHeaders` and `setBody` to `UseChatHelpers`

### ISSUE THREAD

**Issue by bioshazard** [vercel-labs/ai#189]
Seems related to #131 

If there was an additional `setMetadata` function or two `setHeaders` and `setBody` added to the returned chat and completion helpers object we could set headers for auth and body as needed synchronously before any call. I have a use case where I need to set a new auth token for every few calls as the token expires.

Like...

```
const setMetadata = ({ headers, body }) => {
    if(headers) {
      extraMetadataRef.current = {
        ...extraMetadataRef.current,
        headers
      }
    }
    if(body) {
      extraMetadataRef.current = {
        ...extraMetadataRef.current,
        body
      }
    }
```

I think I see where to add it but I am not sure how to develop in a published NPM library... Will try to study some to wrap my head around how to maybe contribute this in a PR. Any tips are welcome. 

EDIT: Am I correct to simply clone the repo, `pnpm i` then `pnpm run dev` with a symlink to my `node_modules` folder? Sorry if that is an extremely novice question. Never contributed to NPM lib before.

**Comment by shuding** [comment]
I’d avoid creating extra methods but accepting body and headers in existing methods, because setting options and triggering requests need to be transactional, and this makes it simpler.

For example:

```js
complete('prompt', {
  body: { ... }
})
```

**Comment by bioshazard** [comment]
@shuding sounds good. Any tips on how to test this locally against my own React app? I tried digging into `npm link` and even copying the full built `packages/core` folder into `node_modules/ai`. Or should I only try to get it working within the test sites in the library. I have an enterprise application for this and so I need to make urgent progress on unblocking this headers override to pass my changing Bearer token or I need to go back to my custom `useChat` I built 2 days before my buddy told me about this superior library lol

**Comment by bioshazard** [comment]
Currently trying my hand at implementing this in the `next-langchain` example.

**Comment by bioshazard** [comment]
Sorry to spam, but using the `next-langchain` example, I was able to get precisely the functionality I wanted included in the `apply` method following your recommendation:

```
const append = useCallback(
    async (message: Message | CreateMessage, metadata?: Object) => {
      
      if(metadata) {
        console.log(metadata)
        console.log(extraMetadataRef.current)
        extraMetadataRef.current = {
          ...extraMetadataRef.current,
          ...metadata
        }
        console.log(extraMetadataRef.current)
      }

      if (!message.id) {
        message.id = nanoid()
      }
      return trigger(messagesRef.current.concat(message as Message))
    },
    [trigger]
  )
```

Will look at seeing if there is a smooth way to deliver this override in a broader capacity and get a PR out for y'alls review maybe tmw.

**Comment by bioshazard** [comment]
I added a simple `metadata` key to permit override of both `body` and `headers`. Worked well against my custom API to override the auth header with a valid token post-instantiation. Looking forward to your thoughts. My first real open source contribution so feel free to nitpick. Thanks for the support!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is an API expansion for per-request headers and body metadata, not a failure of documented existing behavior.

### Evidence
- The issue requests new helpers or method options to update request headers and body before chat/completion calls.
- The use case is refreshing an expiring authentication token after hook instantiation.
- A maintainer suggests extending existing methods transactionally, e.g. `complete('prompt', { body: ... })`, rather than adding setters.
