### ISSUE TITLE
Formatting response in streaming

### ISSUE THREAD

**Issue by reveurguy** [vercel-labs/ai#194]
How can we format response while we stream the api output so that the output looks better.
currently the output is printed as a whole block of text and no new lines, indentation is present.
So how can we format the streaming response for some general style like new lines, spaces, indentations so that the output looks better.
Also how can we use custom styling, like making some text bold, adding markdown for code block etc.
Is there any library that can handle this?

**Comment by Distortedlogic** [comment]
this can be handled with vanilla css on the frontend

**Comment by cephalization** [comment]
You can take some inspiration from the vercel chatbot template.

https://github.com/vercel-labs/ai-chatbot

For newlines and indentation, you can simply apply `white-space: pre-line` to whatever element renders content from gpt

For markdown, you can use Remark, like in that template above, but its slightly more complicated depending on your framework and SSR.

**Comment by reveurguy** [comment]
Ok i'll have a look.
Thanks a lot!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a usage/support question resolved through frontend styling and Markdown-rendering suggestions, not a bug or a request to change the SDK, documentation, or examples.

### Evidence
- The issue asks how to style and format streamed text, including whitespace, bold text, and Markdown.
- Comments provide CSS (`white-space: pre-line`), Remark, and an existing chatbot template as support guidance.
- The reporter confirms they will review the suggested resources; no broken SDK behavior or requested repository change is identified.
