### ISSUE TITLE
Feedback for “Getting Started”

### ISSUE THREAD

**Issue by raamponsah** [vercel-labs/ai#195]
A number of things are missing:
We need to indicate that if the developer wants to use UseCompletion, then the api route must set in the /api/completion/route folder 
if he or she uses useChat then api/chat/route this must be clearly state.
Futher, we need clarity between the difference between useCompletion and useChat as on the npm page it is useChat that is used

**Comment by shuding** [comment]
> We need to indicate that if the developer wants to use UseCompletion, then the api route must set in the /api/completion/route folder
> if he or she uses useChat then api/chat/route this must be clearly state.

The API endpoint can be specified via an `api` option, please check the related API references and type definitions (https://sdk.vercel.ai/docs/api-reference/use-chat#use-chat-options).

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This is a request to clarify and improve written guidance, not a report of broken SDK behavior.

### Evidence
- The issue requests clearer Getting Started guidance on API route configuration for `useCompletion` and `useChat`.
- It also asks the documentation to explain the difference between `useCompletion` and `useChat`.
- A maintainer clarified that the endpoint is configurable through the documented `api` option.
