### ISSUE TITLE
Got a "Type error: Cannot find module 'openai-edge' or its corresponding type declarations." after installation

### ISSUE THREAD

**Issue by ghost** [vercel-labs/ai#212]
Please see the issue created at: "https://github.com/vercel-labs/ai/discussions/211".

**Comment by shuding** [comment]
Can you share your `tsconfig.json`?

**Comment by aryan877** [comment]
any solution ?

**Comment by aryan877** [comment]
facing the same build error, any solution ?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
The issue reports a concrete installation/build failure involving a missing module or type declarations. It is best classified as a bug, though confidence is limited by the lack of configuration and reproduction details.

### Evidence
- The reporter encountered a TypeScript build error after installation: "Cannot find module 'openai-edge' or its corresponding type declarations."
- Another user confirmed encountering the same build error.
- A maintainer requested the reporter's tsconfig.json, but no resolution or reproduction details were provided.
