### ISSUE TITLE
What is the intended scope of this library?

### ISSUE THREAD

**Issue by bioshazard** [vercel-labs/ai#213]
Request: Add a `.md` somewhere defining the intended limits of the features of this library.

I have adopted this library to deliver client/server solutions for handling basic LLM chat experience (loving it btw ty). I want to make sure I am outsourcing functionality wherever possible to limit my maintenance overhead. With that in mind, what kind of functionality is in scope for this specific library? What is for sure permanently out of scope? Here are some examples of functionality I have either finished or have stubbed out that I would like to know if I should pitch or contribute to this specific library:

- Client-side auto-truncate messages payload to context max (currently planning to wrap useChat in a truncate handler to manage messages state prior to new appends)
- Server-side auto-truncate messages payload to context max (currently pre-processing messages payload before .call)
- Server-side streaming messages + completion token counting
- SSE streaming to send `token` events as type "token" which enables addition non-token events like `status` (probably doable in a custom callback)
- Caching `messages` to a database for later recall

Or is the library too new to ask about a strict scope? Or a roadmap to demonstrate the expected scope? Thank you!!

**Comment by MaxLeiter** [comment]
All of these suggestions seem within scope and PRs would be welcome. If it improves the developer experience working with LLM's it's a good fit, IMO. 

> Client-side auto-truncate messages payload to context max

> Server-side auto-truncate messages payload to context max (currently pre-processing messages payload before .call)

My worry with these two suggestions is they might be unexpected for developers. I think it'd be better to throw an error and let the users handle it (and make it easy for them to do so), or add configuration options.  

> completion token counting
There's some discussion around this in #85 

> Caching messages to a database for later recall
Have you seen our recipe in the docs? https://sdk.vercel.ai/docs/concepts/caching

**Comment by bioshazard** [comment]
Thanks for the response. I had not seen that resource, thanks. I had to stop using this library to stream status events along with tokens. I assume it's extensible to that end, but I didn't have the time to dig into it before my last deadline. I'll probably follow up later to see what options I have to return to this library. Gonna close issue this given your scope guidance, that all made good sense ty.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This is a request to document and clarify the library’s intended scope, rather than to change or repair product behavior.

### Evidence
- The issue explicitly requests adding a Markdown document defining the library’s intended feature scope and exclusions.
- The maintainer provides scope guidance and notes that the proposed capabilities generally fit the library.
- The reporter closes the issue after receiving that guidance; no broken SDK behavior is identified.
