### ISSUE TITLE
Stream Functionality Issues with Next.js Deployed in a Docker Container

### ISSUE THREAD

**Issue by samihamine** [vercel-labs/ai#215]
Hello,

I've been encountering some issues with the streaming functionality of Next.js OpenAIStream when it's deployed in a Docker container. The streaming feature works perfectly in a localhost environment, however, I cannot achieve the same functionality when the app is containerized in Docker.

The container is set up with Node.js 18. My questions are:

**Is the streaming functionality designed to work exclusively on the Vercel Edge or is it also expected to function in Docker containers?
If it should work in a Docker environment, are there any specific configurations or steps I need to follow to enable this?
Your assistance and any guidance on addressing this issue would be greatly appreciated.**

I'm using **"node:18-bullseye"** as a Dev Container : <https://github.com/microsoft/vscode-dev-containers/tree/main/containers/javascript-node>

And here is a simplified version of my server implementation: (Nextjs/openAI)

```typescript
import { Configuration, OpenAIApi } from 'openai-edge'
import { OpenAIStream, StreamingTextResponse } from 'ai'

// Create an OpenAI API client (that's edge friendly!)
const config = new Configuration({
  apiKey: process.env.OPENAI_API_KEY
})

const openai = new OpenAIApi(config)

// IMPORTANT! Set the runtime to edge
export const runtime = 'edge'

export async function POST(req: Request): Promise<StreamingTextResponse> {
  // Extract the `prompt` from the body of the request
  const { messages } = await req.json()

  // Ask OpenAI for a streaming chat completion given the prompt
  const response = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo',
    stream: true,
    temperature: 0.7,
    messages,
  })


  // Convert the response into a friendly text-stream
  const stream = OpenAIStream(response)

  // Respond with the stream
  return new StreamingTextResponse(stream)
}
```

```typescript
import { useChat } from 'ai/react'

import type { CustomNextPage } from '@/common/types/page'

const Chatpage: CustomNextPage = () => {
  const { messages, input, handleInputChange, handleSubmit } = useChat()

  return (
    <div>
      {messages.length > 0
        ? messages.map(m => (
            <div key={m.id} >
              {m.role === 'user' ? 'User: ' : 'AI: '}
              {m.content}
            </div>
          ))
        : null}

      <form onSubmit={handleSubmit}>
        <input
    
          value={input}
          placeholder='Say something...'
          onChange={handleInputChange}
        />
      </form>
    </div>
  )
}

export default Chatpage

```

It works well on localhost but not in a docker container.

Looking forward to your feedback.
Thanks

**Comment by EduardoFazolo** [comment]
Could you show us what error it is? I'm assuming it's CORS because `await openai.createChatCompletion(...` will request data from open-ai's API.
I'm pretty sure that if you're going to use Next on a docker container you need a `reverse proxy` [which you can do with NGINX.](https://maximillianxavier.medium.com/solving-cors-problem-on-local-development-with-docker-4d4a25cd8cfe)

Sorry for not elaborating more, I have only set up the reverse proxy once, so I barely know how to do it. I just wanted to give you an starting point for solving this, hope it helps.

**Comment by shuding** [comment]
> Is the streaming functionality designed to work exclusively on the Vercel Edge or is it also expected to function in Docker containers?

No, this library doesn't rely on any special infra. Since it's working correctly on localhost as you tested, it should behave the same when it's inside Docker. So it's likely something related to your container that is misconfigured like @EduardoFazolo said. Might be helpful to investigate based on the actual error or behavior.

**Comment by samihamine** [comment]
Thank you for your responses, @EduardoFazolo and @shuding. I have a setup with Nginx that's acting as a reverse proxy, so that's something I should look into.

I will review the configurations tomorrow and share the feedback with you. If it is indeed a CORS issue or related to the proxy setup, hopefully, I should be able to identify it with a deeper dive into the setup. Thanks again for the tip, it gives me a good starting point for my investigation.

**Comment by samihamine** [comment]
After some research and testing, I finally found the source of the problem.

To put things in context, I was having an issue with the streaming functionality of my dev environment. The setup includes a dev container behind an Nginx server on a VPS. I was able to receive the OpenAI response in the chat, but it came all at once, rather than in a streamed manner as expected.

The root of the problem turned out to be the **buffering in Nginx**. Once I disabled it, the streaming functionality was restored. However, it's worth noting that disabling buffering might have an impact on performance.

Here's how to disable it:

```config
server {
    listen 80;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        # Disable buffering
        proxy_buffering off;
    }
}
```

That said, there might be a better way to disable buffering for specific routes. But, it could require synchronization between the Nginx configuration and the routes managed by Next.js, which would be more a question of organization.

I appreciate the guidance and the tips. Thanks, @EduardoFazolo for pointing me in the right direction.

**Comment by samihamine** [comment]
After some research and testing, I finally found the source of the problem.

To put things in context, I was having an issue with the streaming functionality of my dev environment. The setup includes a dev container behind an Nginx server on a VPS. I was able to receive the OpenAI response in the chat, but it came all at once, rather than in a streamed manner as expected.

The root of the problem turned out to be the **buffering in Nginx**. Once I disabled it, the streaming functionality was restored. However, it's worth noting that disabling buffering might have an impact on performance.

Here's how to disable it:

```config
server {
    listen 80;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        # Disable buffering
        proxy_buffering off;
    }
}
```

That said, there might be a better way to disable buffering for specific routes. But, it could require synchronization between the Nginx configuration and the routes managed by Next.js, which would be more a question of organization.

I appreciate the guidance and the tips. Thanks, @EduardoFazolo for pointing me in the right direction.

**Comment by bibble235** [comment]
Thank you so much for the nginx tip. This should be in capital letters on Vercel. Several nights of my own time as no one will understand the effort.

**Comment by E1NSER** [comment]
> After some research and testing, I finally found the source of the problem.
> 
> To put things in context, I was having an issue with the streaming functionality of my dev environment. The setup includes a dev container behind an Nginx server on a VPS. I was able to receive the OpenAI response in the chat, but it came all at once, rather than in a streamed manner as expected.
> 
> The root of the problem turned out to be the **buffering in Nginx**. Once I disabled it, the streaming functionality was restored. However, it's worth noting that disabling buffering might have an impact on performance.
> 
> Here's how to disable it:
> 
> ```
> server {
>     listen 80;
> 
>     location / {
>         proxy_pass http://localhost:3000;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection 'upgrade';
>         proxy_set_header Host $host;
>         proxy_cache_bypass $http_upgrade;
> 
>         # Disable buffering
>         proxy_buffering off;
>     }
> }
> ```
> 
> That said, there might be a better way to disable buffering for specific routes. But, it could require synchronization between the Nginx configuration and the routes managed by Next.js, which would be more a question of organization.
> 
> I appreciate the guidance and the tips. Thanks, @EduardoFazolo for pointing me in the right direction.

Disabling the buffering did the trick!!! 🍻

**Comment by hengki01** [comment]
> After some research and testing, I finally found the source of the problem.
> 
> To put things in context, I was having an issue with the streaming functionality of my dev environment. The setup includes a dev container behind an Nginx server on a VPS. I was able to receive the OpenAI response in the chat, but it came all at once, rather than in a streamed manner as expected.
> 
> The root of the problem turned out to be the **buffering in Nginx**. Once I disabled it, the streaming functionality was restored. However, it's worth noting that disabling buffering might have an impact on performance.
> 
> Here's how to disable it:
> 
> ```
> server {
>     listen 80;
> 
>     location / {
>         proxy_pass http://localhost:3000;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection 'upgrade';
>         proxy_set_header Host $host;
>         proxy_cache_bypass $http_upgrade;
> 
>         # Disable buffering
>         proxy_buffering off;
>     }
> }
> ```
> 
> That said, there might be a better way to disable buffering for specific routes. But, it could require synchronization between the Nginx configuration and the routes managed by Next.js, which would be more a question of organization.
> 
> I appreciate the guidance and the tips. Thanks, @EduardoFazolo for pointing me in the right direction.



I can't thank you enough. I've been debugging like the whole day before found this post.

**Comment by wowtah** [comment]
> The root of the problem turned out to be the **buffering in Nginx**. Once I disabled it, the streaming functionality was restored. However, it's worth noting that disabling buffering might have an impact on performance.

Awesome find, did the trick for me as well. To keep most of the performance in tact, I opted to only put it on my specific api-route. 

```
 location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_read_timeout 60;
        proxy_connect_timeout 60;
        proxy_redirect off;

        # Allow the use of websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;


        # Nested location for /api/assistant
        location /api/assistant {
            proxy_pass http://127.0.0.1:3000;
            proxy_buffering off;
        }
    }
```

I had to repeat

`proxy_pass http://127.0.0.1:3000;`

in the nested location for some reason.. But works like a charm now. Thanks!

**Comment by gin337** [comment]
> After some research and testing, I finally found the source of the problem.
> 
> To put things in context, I was having an issue with the streaming functionality of my dev environment. The setup includes a dev container behind an Nginx server on a VPS. I was able to receive the OpenAI response in the chat, but it came all at once, rather than in a streamed manner as expected.
> 
> The root of the problem turned out to be the **buffering in Nginx**. Once I disabled it, the streaming functionality was restored. However, it's worth noting that disabling buffering might have an impact on performance.
> 
> Here's how to disable it:
> 
> ```
> server {
>     listen 80;
> 
>     location / {
>         proxy_pass http://localhost:3000;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection 'upgrade';
>         proxy_set_header Host $host;
>         proxy_cache_bypass $http_upgrade;
> 
>         # Disable buffering
>         proxy_buffering off;
>     }
> }
> ```
> 
> That said, there might be a better way to disable buffering for specific routes. But, it could require synchronization between the Nginx configuration and the routes managed by Next.js, which would be more a question of organization.
> 
> I appreciate the guidance and the tips. Thanks, @EduardoFazolo for pointing me in the right direction.

Thanks man, this really helped me out so damn much. GJ!!

**Comment by lufutu** [comment]
> After some research and testing, I finally found the source of the problem.
> 
> To put things in context, I was having an issue with the streaming functionality of my dev environment. The setup includes a dev container behind an Nginx server on a VPS. I was able to receive the OpenAI response in the chat, but it came all at once, rather than in a streamed manner as expected.
> 
> The root of the problem turned out to be the **buffering in Nginx**. Once I disabled it, the streaming functionality was restored. However, it's worth noting that disabling buffering might have an impact on performance.
> 
> Here's how to disable it:
> 
> ```
> server {
>     listen 80;
> 
>     location / {
>         proxy_pass http://localhost:3000;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection 'upgrade';
>         proxy_set_header Host $host;
>         proxy_cache_bypass $http_upgrade;
> 
>         # Disable buffering
>         proxy_buffering off;
>     }
> }
> ```
> 
> That said, there might be a better way to disable buffering for specific routes. But, it could require synchronization between the Nginx configuration and the routes managed by Next.js, which would be more a question of organization.
> 
> I appreciate the guidance and the tips. Thanks, @EduardoFazolo for pointing me in the right direction.

you saved my life <3

**Comment by kozanakyel** [comment]
Actually i want to say thanks for this issue. I have spent lots of time for this organization. Finally i can add a liitle trick if you use docker for nginx you must stop your VPS NGINX then you must restart your docker nginx or loadbalancer for showing your streaming behaviour on your app.

**Comment by zbeyens** [comment]
For those using Coolify, the solution is to disable gzip compression.

**Comment by chiragsrvstv** [comment]
I'm using next 15, running with node. 
After adding these headers without the disabled buffering to my nginx conf made it work for me. Thanks so much!



> After some research and testing, I finally found the source of the problem.
> 
> To put things in context, I was having an issue with the streaming functionality of my dev environment. The setup includes a dev container behind an Nginx server on a VPS. I was able to receive the OpenAI response in the chat, but it came all at once, rather than in a streamed manner as expected.
> 
> The root of the problem turned out to be the **buffering in Nginx**. Once I disabled it, the streaming functionality was restored. However, it's worth noting that disabling buffering might have an impact on performance.
> 
> Here's how to disable it:
> 
> ```
> server {
>     listen 80;
> 
>     location / {
>         proxy_pass http://localhost:3000;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection 'upgrade';
>         proxy_set_header Host $host;
>         proxy_cache_bypass $http_upgrade;
> 
>         # Disable buffering
>         proxy_buffering off;
>     }
> }
> ```
> 
> That said, there might be a better way to disable buffering for specific routes. But, it could require synchronization between the Nginx configuration and the routes managed by Next.js, which would be more a question of organization.
> 
> I appreciate the guidance and the tips. Thanks, @EduardoFazolo for pointing me in the right direction.

**Comment by mariohamann** [comment]
Disabling `proxy_buffering` can lead to unwanted behaviour. Unfortunately there is no way to set it dynamically inside NGINX e. g. based on POST requests or similar.

I just want to share another solution, which is possible due to the fact that NGINX respects `X-Accel-Buffering` to turn off buffering:

```ts
// middleware.ts
import { NextRequest, NextResponse } from 'next/server';

export async function middleware(request: NextRequest) {
  // Add no buffering header for server actions to allow streaming
  const response = NextResponse.next();

  if (request.headers.get('next-action')) {
    response.headers.set('X-Accel-Buffering', 'no');
  }

  return response;
}
```

This worked well for me.

**Comment by Anffernado** [comment]
Thanksss man!!!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a deployment support/configuration question resolved as an Nginx buffering issue external to the AI SDK, not a product bug or explicit documentation request.

### Evidence
- The reporter asks whether streaming is supported in Docker and what configuration is required.
- A maintainer states that the SDK does not depend on special infrastructure and should behave identically in Docker.
- The reporter confirms the cause was Nginx buffering and that disabling it restored streaming.
- Subsequent comments describe reverse-proxy configuration workarounds rather than an AI SDK defect.
