### ISSUE TITLE
Support passing a function when initializing the provided hooks

### ISSUE THREAD

**Issue by Anveio** [vercel-labs/ai#219]
### Use Cases

1. The API I hit depends on some metadata about the messages (messages of length === 1 should hit some other API to create a conversation row in addition to sending a message)

Suggested API:

```typescript
const { messages } = useChat((state)=> {
  return {
    api: state.messages.length === 1 ? `api/create-conversation-with-message` : `api/create-message`
  }
})
```

2. The custom body or headers depends on some metadata about the messages. For example, an API that's trying to minimize data transferred over the network, especially for large conversations, would accept a message, a conversation ID, and an optional index of the message (the index is for the case where you edit an existing message) rather than the entire conversations array, which could be very large. The API would handle pulling the entire conversation and its messages from the DB and inserting the message at the requested index.

Suggested API

```typescript
const { messages } = useChat((state)=> {
  return {
    body: {
      message: state.messages.length[state.messages.length - 1],
      conversationId: props.conversationId, // Outside the scope of this library, so assume it comes from another part of the application
      index: componentState.currentlyEditingMessageIndex // Editing messages I'm assuming is done with just modifying the messages array in place with the current implementation, but a backend optimizing for minimal request/response size might use an entirely different API.
    }
  }
})
```

3. The API I hit depends on some input. For example, if I pass a blank `input` maybe I want to hit an API that generates a useful input for the user

Suggested API

```typescript
const { input } = useChat((state)=> {
  return {
     api: state.input === "" ? `/api/get-useful-prompt` : `/api/create-message`
     // Simplified handling of response below
     onResponse:  (res) => res.body.usefulPrompt ? state.setInput(res.body.usefulPrompt) : state.setMessages(res.body.messages)
  }
})
```

To support these cases I suggest modifying the type of `UseChatOptions`

Before:

```typescript
type UseChatOptions = {
    api?: string;
    id?: string;
    initialMessages?: Message[];
    initialInput?: string;
    onResponse?: (response: Response) => void;
    onFinish?: (message: Message) => void;
    onError?: (error: Error) => void;
    body?: object;
    sendExtraMessageFields?: boolean;
};
```
After:

```typescript
type UseChatOptions =
  | {
    // ... <original UseChatOptions
  }
    | ((state: UseChatHelpers ) => UseChatOptions)
```

The same modification can be ported over to `useCompletion` as well quite trivially I think.

**Comment by shuding** [comment]
Maybe you can do this:

```tsx
const [api, setApi] = useState('api/create-message')

const { messages } = useChat({ api })

useEffect(() => {
  if (messages.length === 1) {
    setApi('api/create-conversation-with-message')
  }
}, [messages.length])
```

And for other options as well.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new dynamic hook-configuration capability rather than reporting a failure of documented behavior.

### Evidence
- Requests allowing `useChat` and `useCompletion` options to be supplied as a function of current hook state.
- Proposes expanding `UseChatOptions` with a callback-based API for dynamically selecting endpoints, bodies, headers, and response handlers.
- Maintainer suggests using React state and `useEffect` as a workaround with the existing API.
