### ISSUE TITLE
Streaming response with langchain hangs 

### ISSUE THREAD

**Issue by sullyo** [vercel-labs/ai#231]
Currently trying to use langchain to stream a response back. I'm noticing that the stream never ends, and the request just hangs. 

For reference here is what i'm doing (identical to the vercel docs - just using pages instead of app)
```
 const { messages, model } = (await req.json()) as RequestBody
    const { stream, handlers } = LangChainStream()

    const llm = new ChatOpenAI({
      streaming: true,
      callbacks: [handlers],
      openAIApiKey: process.env.OPENAI_API_KEY,
    })
    handlers.handleLLMError = async (err) => {
      console.log("LLM Error", err)
    }
    handlers.handleLLMNewToken = async (tokens) => {
      console.log("LLM New Tokens", tokens)
    }
    handlers.handleChainEnd = async () => {
      console.log("Chain ended")
    }


    llm
      .call(
        (messages as Message[]).map((m) =>
          m.role == "user"
            ? new HumanChatMessage(m.content)
            : new AIChatMessage(m.content)
        )
      )
      .catch(console.error)
    return new StreamingTextResponse(stream)
```

I can see the callback is working, but only for new tokens:
   
```
    LLM New Tokens 
LLM New Tokens Hello
LLM New Tokens  there
LLM New Tokens !
LLM New Tokens  How
LLM New Tokens  may
LLM New Tokens  I
LLM New Tokens  assist
LLM New Tokens  you
LLM New Tokens  today
LLM New Tokens ?
LLM New Tokens
```

Is this an issue with langchain? I tried both 0.096 and 0.097

**Comment by swiecki** [comment]
try replacing

``` typescript
const llm = new ChatOpenAI({
      streaming: true,
      callbacks: [handlers],
      openAIApiKey: process.env.OPENAI_API_KEY,
    })
    handlers.handleLLMError = async (err) => {
      console.log("LLM Error", err)
    }
    handlers.handleLLMNewToken = async (tokens) => {
      console.log("LLM New Tokens", tokens)
    }
    handlers.handleChainEnd = async () => {
      console.log("Chain ended")
    }
```

with 

``` typescript
import { CallbackManager } from "langchain/callbacks"
const llm = new ChatOpenAI({
      streaming: true,
      callbackManager: CallbackManager.fromHandlers(handlers),
      openAIApiKey: process.env.OPENAI_API_KEY,
    })
```

**Comment by sullyo** [comment]
Similar issue, also I believe it's deprecated as well on langchains end `@deprecated — Use callbacks instead`.

Could the issue be related to pages dir vs app dir?

**Comment by aranlucas** [comment]
https://github.com/vercel-labs/ai/pull/201

Until this is merged you can create your own handler like https://github.com/vercel-labs/ai-chatbot/issues/82#issuecomment-1608146300

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete failure in existing streaming integration behavior: responses stream tokens but do not terminate.

### Evidence
- Using `LangChainStream()` with `ChatOpenAI` emits token callbacks but never closes the stream, leaving the request hanging.
- Switching to LangChain's `CallbackManager` did not resolve the failure.
- A commenter linked a pending pull request and suggested a custom handler as a temporary workaround.
