### ISSUE TITLE
AI SDK does not work with LangChain and Vectorstores?

### ISSUE THREAD

**Issue by Coding-Crashkurse** [vercel-labs/ai#232]
Hello,

I I try to use the AI SDK with LangChain and tried FAISS and Redis as Vectorstores for my Project. As I saw in the docs, Streaming requires this line of code:

`export const runtime = 'edge'`

Both FAISS and Redis require to use the `fs` Library to load data, but edge does not support these: https://nextjs.org/docs/pages/api-reference/edge#unsupported-apis

Am I just getting it wrong or is there no way to use these togther?

**Comment by MaxLeiter** [comment]
There's no way to use the `fs` API with the Edge runtime. However, streaming on the Node.js runtime [works when deployed on Vercel](https://vercel.com/blog/streaming-for-serverless-node-js-and-edge-runtimes-with-vercel-functions), but it will be slower and computationally more expensive than the equivalent hosted on the edge. I'm not too familiar with FAISS, but for Redis you can look at [Vercel KV](https://vercel.com/storage/kv) or https://upstash.com/

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a compatibility/support question about runtime constraints, not a confirmed SDK defect or an explicit request to change documentation or product behavior.

### Evidence
- The reporter asks whether AI SDK streaming can be combined with LangChain vector stores that require Node.js `fs`.
- The maintainer explains that `fs` is unavailable in the Edge runtime but that streaming can work on Vercel's Node.js runtime, and suggests Redis alternatives.
