### ISSUE TITLE
Does Vercel AI SDK support page router?

### ISSUE THREAD

**Issue by davepoon** [vercel-labs/ai#233]
Does Vercel AI SDK support API routes using Page Router? If so, do you have documentation about the usage of it?

**Comment by shuding** [comment]
It does. The client code is 100% the same on both `pages/` and `app/`. For the API, you can refer to https://sdk.vercel.ai/docs/api-reference/stream-to-response if you are using the default Node.js runtime with Next.js pages API route. If you are using `export const runtime = 'edge'`, it's almost the same code as https://sdk.vercel.ai/docs/api-reference/openai-stream#chat-model-example.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a support question resolved by pointing to existing documentation, not a report of broken behavior or a request for a concrete documentation change.

### Evidence
- The issue asks whether Pages Router API routes are supported and requests usage documentation.
- A maintainer confirms support and links to the relevant existing API references for Node.js and Edge runtimes.
