### ISSUE TITLE
`streamToResponse` does not stream

### ISSUE THREAD

**Issue by pangao66** [vercel-labs/ai#239]
"Can we use the AI SDK to implement a pure Node backend service? I have looked at the documentation for https://sdk.vercel.ai/docs/api-reference/stream-to-response and deployed it on Vercel. The frontend is implemented using a separate frontend and backend approach, but I have not been able to achieve the typewriter effect with stream flow. How can we achieve this effect?"
能否使用 ai sdk 实现一个纯node后端服务 ， 目前看了文档https://sdk.vercel.ai/docs/api-reference/stream-to-response 这个方案 将其部署在vercel上， 前端使用前后端分离的方案实现的， 没能实现打字机效果stream流式返回，如何才能实现这种效果呢

**Comment by Fechin** [comment]
Hi, Do you have a solution for the same problem I am facing?

**Comment by Fechin** [comment]
I also encountered the same problem until I upgraded from `13.3.4` to `13.4.8`, and then it started working.

**Comment by pangao66** [comment]
It still hasn't been resolved   why it was closed?  @MaxLeiter 
https://sdk.vercel.ai/docs/api-reference/stream-to-response         
the way is only use node   not use nextjs

**Comment by MaxLeiter** [comment]
Sorry, I didn't realize this was a problem with the nodejs runtime. Sounds like a bug upstream somewhere. Can you provide a minimal reproduction?

**Comment by pangao66** [comment]
I copy the code as the document    https://sdk.vercel.ai/docs/api-reference/stream-to-response
here is the result I deployed on the vercel    https://koa-test-oe6g5i2yn-pangao66.vercel.app/

```
import { createServer } from 'http'
import { Configuration, OpenAIApi } from 'openai-edge'
import { OpenAIStream, streamToResponse } from 'ai'
export const runtime = 'edge'
const config = new Configuration({
  apiKey: process.env.OPENAI_API_KEY
})
const openai = new OpenAIApi(config)

const server = createServer(async (req, res) => {
  const aiResponse = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo-16k-0613',
    stream: true,
    messages: [{ role: 'user', content: 'What is love?' }]
  })

  // Transform the response into a readable stream
  const stream = OpenAIStream(aiResponse)

  // Pipe the stream to the response
  streamToResponse(stream, res)
})

server.listen(3000)
```

**Comment by mabry1985** [comment]
I'm experiencing the same issue leveraging an express server and am looking for a fix to the problem as well

**Comment by Hebilicious** [comment]
I've got it working with Nuxt and edge runtime here https://github.com/vercel-labs/ai/pull/295

**Comment by alexyoung23j** [comment]
Same issue (in a serverless function i.e. `api/completion.ts`. Working fine locally, stream is broken in the vercel deployment. node 18 in both cases, upgraded next to 13.4.8 as suggested by @Fechin to no avail.

**Comment by smaeda-ks** [comment]
Hi @alexyoung23j, sorry for the confusion.

Just to be clear, streaming support in Vercel serverless functions is only available in App router, not Pages router. The reason why it worked locally even with Pages router is because there's just only one machine and has no technical constraints, unlike our production infrastructure where multiple (complicated) layers are communicating with each other to make it work. We could perhaps introduce some degradation in the dev server on purpose not to support streaming in Pages router, but anyway, you need to use App router in this case.

**Comment by smaeda-ks** [comment]
@pangao66 if you're using standalone serverless functions without any framework (i.e., you're building your functions using `@vercel/node`), you probably need to add the following code in your function:

```js
export const config = {
  supportsResponseStreaming: true,
}
```

ref. https://github.com/vercel/vercel/blob/4bf2ca55ff64b5994ee386b99d0e491f1a70c00a/packages/node/src/index.ts#L495-L511

**Comment by pangao66** [comment]
it still not solve my problem 
https://sdk.vercel.ai/docs/api-reference/stream-to-response
even I copy the docs   demo code   and  add the code
 `export const config = {
  supportsResponseStreaming: true,
}`
it still not stream response

**Comment by smaeda-ks** [comment]
@pangao66 could you please create a minimal reproducible example repo and share that with us?
https://vercel.com/guides/creating-a-minimal-reproducible-example

**Comment by pangao66** [comment]
here is my source code https://github.com/pangao66/koa-test/blob/master/src/index.ts
here is my vercel result https://koa-test-theta.vercel.app/

**Comment by smaeda-ks** [comment]
@pangao66 we can't access your private repo

**Comment by pangao66** [comment]
@smaeda-ks now is public

**Comment by smaeda-ks** [comment]
@pangao66 so the issue is you're using `tsup` and generating `index.mjs` where any `const` are converted to `var`, causing our analyzer not to be able to catch those config options from your code correctly:
https://github.com/vercel/vercel/blob/9969f0ba18a8588e9aaf8cc8df2bc1d4af30d5ea/packages/static-config/src/index.ts#L46-L69

`@vercel/node` support TypeScript by default so you don't have to use it:
https://vercel.com/docs/concepts/functions/serverless-functions/runtimes/node-js#using-typescript-with-the-node.js-runtime

so maybe try updating your `vercel.json` to specify your `src/index.ts` file directly.

**Comment by arslancodes** [comment]
Hey guys, did anyone manage to fix this issue? If so, please help me. Thanks

**Comment by dkrief** [comment]
Also looking for the answer on this... :(
I tried downgrading my nextjs version but still same issue on production.

**Comment by MaxLeiter** [comment]
Hi @dkrief and @arslancodes, please provide reproductions so we can verify a bug. If you read up in the conversation other people's issues have been user-space and not with the `ai` library or Vercel.

**Comment by qingdog** [comment]
missing export
```js
import { createServer } from 'http'
import { Configuration, OpenAIApi } from 'openai-edge'
import { OpenAIStream, streamToResponse } from 'ai'

const OpenAIConfig = new Configuration({
  apiKey: process.env.OPENAI_API_KEY
})
const openai = new OpenAIApi(OpenAIConfig)
const runtime = "edge";
const config = {
  supportsResponseStreaming: true
};
```
https://github.com/pangao66/koa-test/blob/master/api/index.ts#L10C1-L12C3

**Comment by pangao66** [comment]
@qingdog  it seems your  code also  does not stream
I have tried

**Comment by qingdog** [comment]
> @qingdog it seems your code also does not stream I have tried

Try this link and you should see `Hello world` and streaming replies.
https://koa-test-five.vercel.app/

**Comment by pangao66** [comment]
@qingdog thank you very much  It seems  have been solved, I  use the npm package  `ai`  in web  it also stream

**Comment by Exkalybur** [comment]
We had similar issue, where it was not streaming in production - just loading and then right away returning the full response. However, in dev mode or on preview it was working fine. 
Apparently, at least in our case, it was DNS settings from Cloudflare, we disabled proxying and everything started streaming again. 
Before you update anything, I would suggest checking against your default production domain provided by Vercel, which ends in vercel.app. If that streams, then disabling Cloudflare proxying should solve the issue.

**Comment by jvandenaardweg** [comment]
> Just to be clear, streaming support in Vercel serverless functions is only available in App router, not Pages router (Next.js).

That's not true. I've had streaming working for months using the Pages Router (`/pages/api/whatever`)

**Comment by ivasilov** [comment]
> > Just to be clear, streaming support in Vercel serverless functions is only available in App router, not Pages router (Next.js).
> 
> That's not true? I've had streaming working for months using the Pages Router (`/pages/api/whatever`). Just recently switched some API routes to the App Router.
> 
> > We had similar issue, where it was not streaming in production - just loading and then right away returning the full response. However, in dev mode or on preview it was working fine.
> > Apparently, at least in our case, it was DNS settings from Cloudflare, we disabled proxying and everything started streaming again.
> > Before you update anything, I would suggest checking against your default production domain provided by Vercel, which ends in vercel.app. If that streams, then disabling Cloudflare proxying should solve the issue.
> 
> Experiencing the same. More info here: #633

Which runtime did you use for those API routes? The default is `nodejs`.

**Comment by jvandenaardweg** [comment]
Edge 👍

**Comment by danielpl10** [comment]
Hello everyone, is there a final solution for this? I'm using Next 14.1.3 with Vercel ai 3.0.8, lastes version of everything at this moment, using app router and with the basic example that vercel gives in the vercel ai sdk docs. The streaming works locally and not on the deployment in vercel. If you want an example just try asking "what is css" on this two apps made by some of yourself https://sdk.vercel.ai/ or https://chat.vercel.ai/, can't see any streaming, just the entire response

**Comment by yahorbarkouski** [comment]
experiencing the same error, next 14.1.4

**Comment by rahilvora** [comment]
I am facing same issue on `14.0.1`

**Comment by lgrammel** [comment]
@yahorbarkouski @rahilvora I'm trying to get the root of this and write a troubleshooting guide. Are you using any proxies such as Cloudflare? Which runtime are you using for deployment (edge, node)? Do you have additional configuration for the runtime env? Can you share the relevant code snippet (e.g. `route.ts`)?

**Comment by yahorbarkouski** [comment]
@lgrammel I used no proxies, tried on both domains (mine and vercel's), tried to use both node 20+ / edge runtimes, configuration was pretty much copy pasted from AI stocks example

after a few days of debugging, we were able to fix the issue by enforcing 
```typescript
export const dynamic = 'force-dynamic'
```
on layout level

**Comment by lgrammel** [comment]
@yahorbarkouski awesome, I'll see that this is included in a troubleshooting page

**Comment by rahilvora** [comment]
Hey @lgrammel This is my [route file] (https://github.com/rahilvora/rag-langchain-v2/blob/main/app/api/chat/quick_start/route.ts). I am using `edge` environment. It works locally but does not work on vercel deployment. I am not using Cloudflare proxy

I also tried adding `text/event_stream` content type to my response header but that did not work for me.

**Comment by lgrammel** [comment]
@rahilvora can you try upgrading to the latest Next.js version?

**Comment by rahilvora** [comment]
Hey @lgrammel I updated NextJS version to `14.2.1` [link](https://github.com/rahilvora/rag-langchain-v2/blob/15953c8b1db74f32643a1c15450ca5c9d76ca156/package.json#L31) but it still does not work for me.

**Comment by lgrammel** [comment]
@rahilvora can you add `export const dynamic = 'force-dynamic'` to you route file?

**Comment by ali-issa** [comment]
If you're using ngnix as a reverse proxy on you server you should have `proxy_buffering off;` in your config and increase `proxy_read_timeout` so that responses don't timeout when streaming.

```nginx
...

server {
    listen       443 ssl http2;
    listen       [::]:443 ssl http2;
    server_name example.com;

    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off; # <--- must be off
        proxy_read_timeout 300s; # <--- shouldn't be a low number
    }

    location /static/ {
        alias /path/to/static/files/;
        expires 7d;
        add_header Cache-Control "public";
    }
}

...
```

**Comment by ASAD5401** [comment]
where to add this code?

**Comment by ASAD5401** [comment]
> @lgrammel I used no proxies, tried on both domains (mine and vercel's), tried to use both node 20+ / edge runtimes, configuration was pretty much copy pasted from AI stocks example
> 
> after a few days of debugging, we were able to fix the issue by enforcing
> 
> ```ts
> export const dynamic = 'force-dynamic'
> ```
> 
> on layout level

where we need to add this code ?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a deployment/configuration support thread with several environment-specific causes, not a confirmed AI SDK defect or a direct request to change documentation, examples, or product behavior.

### Evidence
- The reporter asked how to enable streaming in a standalone Node backend deployed on Vercel.
- Maintainers traced the reproduction to `tsup` converting exported `const` declarations to `var`, preventing Vercel from detecting `supportsResponseStreaming`.
- The reporter later confirmed streaming was working after configuration changes.
- Maintainers stated the reproduced problems were user-space or deployment configuration issues rather than defects in the `ai` library.
