### ISSUE TITLE
React js support

### ISSUE THREAD

**Issue by zryann** [vercel-labs/ai#263]
As we know there is no api route in reactjs so how is it possible to use it inside reactjs?
using it inside nextjs is really simple and there is examples, is there any example to use it in reactjs? 

If it cant directly use the same thing inside reactjs as the examples used inside nextjs then whats the solution?

Thank you!

**Comment by samsullivandelgobbo** [comment]
The examples require a backend that returns the stream using SWR if you want to have the streaming functionality, you can implement this on your existing backend or just use nextjs and call your existing backend through the next server and follow the nextjs implementation.

**Comment by zryann** [comment]
@samsullivandelgobbo my problem is i cant use nextjs because the project is built using react and we are working on it, so the only solution for the streaming functionality is add a backend and then put useChat({api: API_URL}) that will work?

**Comment by samsullivandelgobbo** [comment]
It wouldn't work with the streaming. If your frontend is written in react it should be really simple to copy it over to a nextjs environment. It's recommended to use nextjs for new react projects unless you have a more complex project architecture.

**Comment by zryann** [comment]
@samsullivandelgobbo exactly that’s right nextjs is recommended, but it’s a large and complex project and it’s integrated with the electronJS and it’s not easy to convert it to nextjs.

so the streaming will not work sadly, and thank you for you answers and time

**Comment by samsullivandelgobbo** [comment]
You should be able to get SWR working in electron, I don't have much experience with it but it shouldn't be too hard.

**Comment by zryann** [comment]
@samsullivandelgobbo sorry for taking so much time, but if i send the request using SWR to the backend inside the react component will it work? How it will work with the useChat() hook? I think again it will be another problem 🤔

**Comment by samsullivandelgobbo** [comment]
You want to return 

```	
const response = await openai.createChatCompletion({
		model: 'gpt-3.5-turbo-16k-0613',
		stream: true,
		messages,
		functions,
		function_call
	});

	const stream = OpenAIStream(response);
	return new StreamingTextResponse(stream);

``` 
	
on your backend to the react frontend, it should work fine using the useChat hook.

**Comment by MaxLeiter** [comment]
Closing this issue as the SDK should work fine with just Node.js. Feel free to open a discussion if you want to continue sharing your findings or discussing this.

**Comment by Nisthar** [comment]
@zryann Hey, just curious. Have you managed to do this ? for using swr, you have to add a backend server right?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily an implementation/support question rather than a report of broken behavior or a concrete request to change documentation, examples, or product capabilities.

### Evidence
- The reporter asks how to use the SDK and streaming with an existing React/Electron application that lacks a Next.js API route.
- Comments explain that a Node.js backend can return an OpenAI stream for consumption by the React useChat hook.
- A maintainer closed the issue because the SDK should work with Node.js and directed further questions to a discussion.
