### ISSUE TITLE
Nuxt 3 - responseBodyStream.pipeThrough is not a function  at AIStream

### ISSUE THREAD

**Issue by EvandroVV93** [vercel-labs/ai#269]
Following the example for nuxt 3, it worked just fine a few weeks ago but after the update it returns this error:

![image](https://github.com/vercel-labs/ai/assets/73674669/a89e84cb-3d53-4854-a402-205863b56cf4)

Is there a workaround?

Thanks!

**Comment by MaxLeiter** [comment]
Hi, can you try updating to the most recent version? Is it possible your Node.js version changed?

**Comment by EvandroVV93** [comment]
Sorry for the delay, I've have been using Node 18 LTS, the latest version didn't work for me, I've downgraded to 2.1.3 and it's working perfectly right now.

**Comment by MaxLeiter** [comment]
Hi @EvandroVV93 , I still can't reproduce using Node 18 but Node 16 throws this problem. Can you please try [`ai@2.1.26`](https://github.com/vercel-labs/ai/releases/tag/ai%402.1.27)?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete runtime failure and apparent regression in existing AI SDK streaming behavior, with a downgrade serving as a workaround.

### Evidence
- Nuxt 3 integration throws a 500 error: `responseBodyStream.pipeThrough is not a function` in `AIStream`.
- The reporter says the example worked before an update and that downgrading to `ai@2.1.3` restores correct behavior.
- A maintainer confirmed that the failure can occur under Node.js 16, though they could not reproduce it with Node.js 18.
