### ISSUE TITLE
In the chatCompletion utility when the input is send, the input should become blank but at present the input remains the same.

### ISSUE THREAD

**Issue by Cenrax** [vercel-labs/ai#280]
The input stays in the box even after sending. One needs to again delete the previous input to enter a new input

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes a concrete failure in existing chat input behavior: the input is expected to clear after submission but remains populated.

### Evidence
- The chatCompletion utility leaves the submitted text in the input box after sending.
- The reporter must manually delete the previous input before entering another message.
