### ISSUE TITLE
Functions its not working 

### ISSUE THREAD

**Issue by thareekanvarm** [vercel-labs/ai#324]
![Screenshot from 2023-07-13 15-06-54](https://github.com/vercel-labs/ai/assets/117096530/bc096702-754c-4d16-9c28-81e3a3178515)

Please some one help me

**Comment by MaxLeiter** [comment]
Have you updated your `ai` package?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
This is primarily an unresolved support request with insufficient evidence of an AI SDK defect.

### Evidence
- The screenshot shows TypeScript rejecting `experimental_onFunctionCall` as an unknown `AIStreamCallbacks` property.
- The report provides no package version, reproduction steps, or confirmation that the problem persists.
- The maintainer asks whether the `ai` package was updated and the TypeScript server restarted, suggesting a local version/cache issue.
