### ISSUE TITLE
Providing a function to `function_call` in streaming chat completion throws because of `finish_reason: stop`

### ISSUE THREAD

**Issue by shametim** [vercel-labs/ai#329]
OpenAI chat completion  `finish_reason` does not return `function_call` but instead returns `stop` when defining the `function_call` parameter to force it to call a particular function (see repro steps below). 

Because of `finish_reason` in the last chunk being `stop` we don't run [this ](https://github.com/vercel-labs/ai/blob/main/packages/core/streams/openai-stream.ts#L157-L158) hence, the resulting string right after transform flush looks like so: 

`"{\"function_call\": {\"name\": \"log_age\", \"arguments\": \"{}"`

![image](https://github.com/vercel-labs/ai/assets/9932250/c681c7a4-a286-40ac-9d72-6fbbba756396)

[This line throws](https://github.com/vercel-labs/ai/blob/main/packages/core/streams/openai-stream.ts#L235) because the JSON is incomplete (from not adding those last two closing curly braces) and that's what this issue is all about.

Now I would argue this is more on OpenAI not fully adhering to one contract of always marking `finish_reason: function_call` when provided functions with a function_call. 

However I have lower expectations on OpenAI getting this resolved faster than we can patch it here in the meantime.  I will try my best to make another issue on one of the OpenAI repos about it.

Let me know if you want me to take a stab at a fix else thanks for taking your time to look at this and putting together this helpful library!

Related: https://github.com/vercel-labs/ai/pull/311

Steps to reproduce

```
const response = await openai.createChatCompletion({
  model: "gpt-3.5-turbo-0613",
  stream: true,
  messages,
  functions: [
    {
      name: "log_age",
      description: "Call whenever user responds with their age.",
      parameters: {
        type: "object",
        properties: {
          age: {
            type: "number",
            description: "User's age",
          },
        },
      },
    },
  ],
  function_call: { name: "log_age" },
});

const stream = OpenAIStream(response, {
  experimental_onFunctionCall: async (
    { name, arguments: args },
    createFunctionCallMessages
  ) => {
    // Function definition in this case does not matter because the library fails before this point.
    // Only necessary to provide `experimental_onFunctionCall` so that we can invoke `createFunctionCallTransformer`

    return openai.createChatCompletion({
      // @ts-ignore
      messages: [...messages, ...newMessages],
      stream: true,
      model: "gpt-3.5-turbo-0613",
      functions,
    });
  },
});

```

**Comment by shametim** [comment]
Thanks, had been taking a look at this this evening. I think I managed to come up with least intrusive way to go about this in the PR linked.

I felt like the AIStream abstraction and the parser prevented some of the much needed flexibility here with the function streaming feature. 

Imo, maybe eventually we could consolidate the OpenAI stream parsing a bit. We should just need to JSON parse each chunk just once ever and do all of the content and function_call stitching via one TransformStream as opposed to having to work with and around customParser abstraction, thinking out loud here.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a reproducible failure in existing streaming function-call handling: the SDK builds incomplete JSON for a valid response pattern and throws unexpectedly.

### Evidence
- Forcing a specific OpenAI function call in a streaming completion can produce a final chunk with `finish_reason: stop`.
- The stream transformer only closes the constructed function-call JSON for another finish reason, leaving the JSON incomplete.
- The SDK then calls `JSON.parse` on the malformed payload and throws before `experimental_onFunctionCall` runs.
- A maintainer confirmed encountering the same issue and invited a pull request.
