### ISSUE TITLE
Deprecated Imports in LangChain guide

### ISSUE THREAD

**Issue by Taimoor0217** [vercel-labs/ai#332]
The current example in the langChain guide uses imports that have been deprecated.

<img width="2500" alt="image" src="https://github.com/vercel-labs/ai/assets/48244930/9affa5ec-35eb-4ccd-b7ad-ffab5712a2ff">

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This requests correction of code shown in a documentation guide, without alleging broken AI SDK product behavior.

### Evidence
- The issue specifically identifies outdated imports in the LangChain guide's code snippet.
- The attached screenshot shows `AIChatMessage` and `HumanChatMessage` marked deprecated, with guidance to use `HumanMessage` instead.
