### ISSUE TITLE
experimental_onFunctionCall on OpenAIStream calls onStart multiple times

### ISSUE THREAD

**Issue by odysseaspapadimas** [vercel-labs/ai#351]
I'm using experimental_onFunctionCall server-side to get some weather data and a couple of other functions. When the user sends a message for example: What's the weather in New York? The OpenAIStream handler calls onStart, and that's where I save my prompt messages to my database, when it detects the prompt is a function it reruns the onStart causing the user prompt to be saved twice in my database

Any ideas on how to prevent this?

**Comment by MaxLeiter** [comment]
I've opened a PR removing `onStart` and `onCompletion` from the callbacks passed to the recursive calls. thanks!

https://github.com/vercel-labs/ai/pull/357

**Comment by smstromb** [comment]
@MaxLeiter With this change, how does one save the completion result of the function itself (e.g, "It's 70F in New York") to a database without an `onComplete`?

**Comment by MaxLeiter** [comment]
@smstromb can you build it into your function handler?

**Comment by smstromb** [comment]
Example:

```ts
const functions: ChatCompletionFunctions[] = [
  {
    name: 'get_current_weather',
    description: 'Get the current weather',
    parameters: {
      type: 'object',
      properties: {
        location: {
          type: 'string',
          description: 'The city and state, e.g. San Francisco, CA'
        },
        format: {
          type: 'string',
          enum: ['celsius', 'fahrenheit'],
          description:
            'The temperature unit to use. Infer this from the users location.'
        }
      },
      required: ['location', 'format']
    }
  }
]
 
export async function POST(req: Request) {
  const { messages } = await req.json()
 
  const response = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo-0613',
    stream: true,
    messages,
    functions
  })
 
  const stream = OpenAIStream(response, {
    onStart: async () => {
      // save user message to db
    },
    onCompleted: async (completion) => {
      // save assistant response to db
      // Does not include responses from function calls
    },
    experimental_onFunctionCall: async (
      { name, arguments: args },
      createFunctionCallMessages
    ) => {
      if (name === 'get_current_weather') {
        const weatherData = {
          temperature: 20,
          unit: args.format === 'celsius' ? 'C' : 'F'
        }
   
        // Not the messages I'm looking to save
        const newMessages = createFunctionCallMessages(weatherData)

        // I need the response from this completion saved to the db while streaming back to the user
        // E.g, The temperature in San Francisco is 20C
        return openai.createChatCompletion({
          messages: [...messages, ...newMessages],
          stream: true,
          model: 'gpt-3.5-turbo-0613',
          functions
        })
      }
    }
  })

  return new StreamingTextResponse(stream)
}
```

I'd have to change the following:

```ts
    experimental_onFunctionCall: async (
      { name, arguments: args },
      createFunctionCallMessages
    ) => {
      if (name === 'get_current_weather') {
        const weatherData = {
          temperature: 20,
          unit: args.format === 'celsius' ? 'C' : 'F'
        }
   
        // Not the messages I'm looking to save
        const newMessages = createFunctionCallMessages(weatherData)

        // I need the response from this completion saved to the db while streaming back to the user
        // E.g, The temperature in San Francisco is 20C
        const response = await openai.createChatCompletion({
          messages: [...messages, ...newMessages],
          stream: true,
          model: 'gpt-3.5-turbo-0613',
          functions
        })

        const functionStream = OpenAIStream(response, {
             onCompletion: async (completion) => {
                 // save to db
             }
        })

        const reader = functionStream.getReader();
        while (true) {
          const { done } = await reader.read();
          if (done) break;
        }
        
        return response;
      }
    }
```

Which works in terms of capturing the function response but blocks the stream response back to the client while doing so.

**Comment by benvp** [comment]
I don't know if this is the preferred to do it (I'm a noob in regards to Streams) but it works for me. I `clone` the `Response` so it can be read independently and then create a new `OpenAIStream`.

If there is a way to handle this in a better way, I'd appreciate any help.

```ts
// clone response so it can be read independently
const functionStream = OpenAIStream(response.clone(), {
  onCompletion: async (completion) => {
    // do persist here
  },
});

const readResult = async () => {
  const reader = functionStream.getReader();
  while (true) {
    const { done } = await reader.read();
    if (done) break;
  }
};

readResult();

```

**Comment by heymartinadams** [comment]
> @MaxLeiter With this change, how does one save the completion result of the function itself (e.g, "It's 70F in New York") to a database without an `onComplete`?

This is the core issue here.

**Comment by heymartinadams** [comment]
Our app saves the conversation to the database on the server-side, and that’s why an `onComplete` is quite needed, even for function response streams.

**Comment by mosnicholas** [comment]
@MaxLeiter quick thought -- maybe a better function definition for `experimental_onFunctionCall` would be:

`experimental_onFunctionCall?: (functionCallPayload: FunctionCallPayload, createFunctionCallMessages: (functionCallResult: JSONValue) => CreateMessage[]) => ReadableStream;`

The reason for this change would be to return an OpenAI stream from the `experimental_onFunctionCall` method, which would allow us to make the calls actually be recursive. The example that comes to mind is if you have the following function code:

```
const functions: ChatCompletionFunctions[] = [
  {
    name: 'get_current_weather',
    description: 'Get the current weather',
    parameters: {
      type: 'object',
      properties: {
        location: {
          type: 'string',
          description: 'The city and state, e.g. San Francisco, CA'
        },
        format: {
          type: 'string',
          enum: ['celsius', 'fahrenheit'],
          description:
            'The temperature unit to use. Infer this from the users location.'
        }
      },
      required: ['location', 'format']
    }
  }
]
```

and call the chat with the following request: `What's the weather in SF and in NYC?`, we would have to call the function twice sequentially. In the current format, we can't actually accomplish that, we can only call it in one loop (ie. get first function call, call function & synthesize response).

**Comment by MaxLeiter** [comment]
hi all, please see my comment [here](https://github.com/vercel/ai/pull/437#issuecomment-1681388183) and give the version linked a try. I think it will solve this once and for all 🙏

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete callback lifecycle defect in existing function-call streaming behavior that causes duplicate side effects. Maintainer comments confirm it warranted a code change.

### Evidence
- `OpenAIStream` invokes `onStart` again during recursive function-call handling, causing the same user prompt to be persisted twice.
- A maintainer opened PR #357 to stop passing `onStart` and `onCompletion` to recursive calls.
- Later comments identify side effects of that fix for capturing function-call completions, and the maintainer points to a newer proposed solution.
