### ISSUE TITLE
How can I trigger an API call without using handleSubmit?

### ISSUE THREAD

**Issue by yehiaabdelm** [vercel-labs/ai#355]
I'm using svelte, and I want to trigger an API call outside of a form as I have other operations that I need to handle before submitting. What is the preferred way to do this?

Right now I tried something like this, but it isn't working. (this is a very rough sketch)
```js
<script>
let promptId;
let completionId;
const { handleSubmit, completion } = useCompletion({
		api: `/api/openai/completion`,
		body: {
			messages,
			model: 'gpt-3.5-turbo',
			promptId,
			completionId
		},
		id: chatId,
	});

const handleNewMessage = ()=>{
    // ... rest of code (setting promptId, completionId and messages)
    // ... then triggering the API call
    const event = new Event('submit')
    handleSubmit(event)
}

</script>

<div>
    <button on:click={handleNewMessage}>
    Submit
    </button>

</div>



```

I'm using useCompletion and not useChat since it is more customizable.

**Comment by bernaferrari** [comment]
Oh, same. I was going to open the same issue. I have my own form and my own button, I don't want to tie the "handleSubmit" to a form.

**Comment by shuding** [comment]
You can use the `append` API, e.g. `append({ role: 'user', content: input })`. Docs: https://sdk.vercel.ai/docs/api-reference/use-chat#chat-helpers

**Comment by KrishnaCodez** [comment]
hey guys i am using shadcn form can't directly use handleSubmit... then i came see this issue used append but it give me 500 error
. The need for using shadcn is future i need to add more fields 

would appreciate solution 

here is my code

 const { messages, input, handleSubmit, append } = useChat();
  const form = useForm({
    resolver: ArrayToZodResolver(fields),
    defaultValues: {},
  });
  async function onSubmit(data: any) {
    console.log("Form data:", data);
    console.log("Form data:", data);
    try {
      append({
        id: Math.random().toString(),
        role: "user",
        content: data.text,
      });
    } catch (error) {
      console.error("Error from chatHandleSubmit:", error);
    }
  }
  return (
    <>
      {messages.map((message) => (
        <div key={message.id}>
          {message.role === "user" ? "User: " : "AI: "}
          {message.content}
        </div>
      ))}

      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)}>
          <CardContent>
            <div className="grid grid-cols-3 gap-4 max-md:grid-cols-1">
              {fields.map(({ config, RenderComponent }, i) => (
                <div key={i} className="flex flex-col gap-2">
                  <RenderComponent {...config} control={form.control} />
                </div>
              ))}
            </div>
            <Button type="submit" className=" my-6 w-full">
              Continue
            </Button>
          </CardContent>
        </form>
      </Form>
    </>

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage/support question about invoking chat or completion helpers programmatically, not a confirmed SDK bug or a request to change product behavior, documentation, or examples.

### Evidence
- The original report asks how to trigger a request outside a form and describes a rough attempted workaround.
- A maintainer answers with the existing `append` API and links its documentation.
- The later report of a 500 error lacks server details or a reproducible case demonstrating an SDK defect.
