### ISSUE TITLE
Feedback for “Getting Started”

### ISSUE THREAD

**Issue by numenbit** [vercel-labs/ai#385]
Is the sdk.vercel.ai website open source?   Or is there something similar that would demonstrate the chat panels side by side using different models for comparisons.   Would be a good example template to use if planning on using replicate and Vercel for custom models. 

Looking at needing something similar where there are two chat panels running against different models.  

Curious to see if that code is also open source or are there any example templates that demonstrate something similar that use next.js

**Comment by MaxLeiter** [comment]
It isn't open-source but you can see an open-source chatbot from us here: https://github.com/vercel-labs/ai-chatbot

Supporting multiple models is mostly a matter of using the `useChat` hook multiple times with different options/API routes.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a question and support request about locating or implementing an example, not a concrete request to change the SDK, documentation, or repository examples.

### Evidence
- The reporter asks whether sdk.vercel.ai is open source and whether an existing Next.js template demonstrates two chat panels using different models.
- The maintainer answers that the site is not open source, links an existing open-source chatbot, and explains that multiple hooks and API routes can support multiple models.
