### ISSUE TITLE
Catch errors

### ISSUE THREAD

**Issue by satpalsr** [vercel-labs/ai#390]
Look at [HF stream](https://sdk.vercel.ai/docs/guides/huggingface#create-a-route-handler) for instance.
Try-catch blocks don't work here when I pass wrong HF Token, as asyncgenerator object is returned.
Add examples catching the error in docs.
```
 error Error: Authorization header is correct, but the token seems invalid
    at streamingRequest (webpack-internal:///(sc_server)/./node_modules/.pnpm/@huggingface+inference@2.6.1/node_modules/@huggingface/inference/dist/index.mjs:323:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async textGenerationStream (webpack-internal:///(sc_server)/./node_modules/.pnpm/@huggingface+inference@2.6.1/node_modules/@huggingface/inference/dist/index.mjs:659:5) {
  digest: undefined
}
```

**Comment by MaxLeiter** [comment]
You can check the `request` object's status / `ok` field to determine if you'd like to process it as a stream. I can update the docs.

**Comment by satpalsr** [comment]
Sorry not clear on what you suggested. For OpenAI I can do
```
res = await openai.createChatCompletion({
      model: selectedModel,
      messages,
      temperature: 0.7,
      stream: true
    })
    
      if (res.status !=200) {
    return new Response('Some error',{ status: res.status, statusText: 'Some error',});
  }
    ```
    
But this does not work for HuggingFace

**Comment by hypnocill** [comment]
@satpalsr did you find how to error handle huggingface errors?

**Comment by matthiaslau** [comment]
@MaxLeiter can we please reopen this issue? It is about not being able to catch errors on the server when using Hugginface. This for example doesn't catch errors, while it works for openai:

`try {
    const response = Hf.textGenerationStream({
      model: model,
      inputs: experimental_buildLlama2Prompt(messages),
    });

    const stream = HuggingFaceStream(response);
    return new StreamingTextResponse(stream);
  } catch (error) {
    console.log("Error");
  };`

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
Although the original report also requests documentation examples, it describes a concrete error-handling failure in the existing Hugging Face streaming integration. Per the maintainer comment, the uncaught `onError` behavior is an existing bug tracked elsewhere.

### Evidence
- Hugging Face streaming errors, such as an invalid token, occur during async-generator iteration and are not caught by the surrounding try/catch.
- A maintainer identified the failure to be caught by `onError` as a duplicate of issue #358.
- A later comment confirms the server-side error remains uncatchable with `HuggingFaceStream`, while comparable OpenAI handling works.
