### ISSUE TITLE
onComplete does not get triggered when returning a new response in experimental_onFunctionCall

### ISSUE THREAD

**Issue by juliuslipp** [vercel-labs/ai#412]
Hey guys,

nice library btw.

When returning a new response in experimental_onFunctionCall, the onCompletion hook is not called triggered for its response. 

It is triggered with the unparsed functioncall however (unexpected from my opinion).
```ts
import {
    Configuration,
    OpenAIApi,
    type ChatCompletionRequestMessage,
} from "openai-edge";

const configuration = new Configuration({
    apiKey: env.OPENAI_API_KEY,
});

const openai = new OpenAIApi(configuration)
// ...

const stream = OpenAIStream(res, {
    onCompletion: async (completion) => {
        // triggered with unparsed fncall, but without completion from new response created in experimental_onFunctionCall
    },
    experimental_onFunctionCall: async (
        {name, arguments: args},
        createFunctionCallMessages,
    ) => {
        // ...
        const result = "123";
        const newMessages = [
            ...messages,
            ...createFunctionCallMessages(result),
        ];

       // Response does not appear in onCompletion
        return await openai.createChatCompletion({
            model: "gpt-3.5-turbo",
            messages: newMessages
            temperature: 0.7,
            stream: true,
            functions: consultationFunctions,
        })
    });
```

**Comment by juliuslipp** [comment]
just found #351

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes a concrete callback failure in existing streaming/function-call behavior. Although it may duplicate another issue, the underlying report is clearly a bug.

### Evidence
- `onCompletion` is called with the unparsed function call but not with the completion from the response returned by `experimental_onFunctionCall`.
- The report includes code reproducing the missing callback behavior.
- The reporter notes that issue #351 describes the same problem.
