### ISSUE TITLE
Issue deploying in Vercel: Missing auth?

### ISSUE THREAD

**Issue by zajcomm** [vercel-labs/ai#419]
Pleaes see first few lines of the deployment error:
it says missing auth, even though I did provide openAI API key, but wondering if its refereing to another auth?

ext-replicate:build:
--
17:40:04.825 | next-replicate:build: Error: Missing required parameter: auth
17:40:04.825 | next-replicate:build:     at new c (/vercel/path0/examples/next-replicate/.next/server/app/api/chat/route.js:18:22360)
17:40:04.825 | next-replicate:build:     at 278 (/vercel/path0/examples/next-replicate/.next/server/app/api/chat/route.js:13:39543)
17:40:04.826 | next-replicate:build:     at __webpack_require__ (/vercel/path0/examples/next-replicate/.next/server/edge-runtime-webpack.js:25:42)
......

**Comment by MaxLeiter** [comment]
It seems like you're trying to build the replicate example, so you need to pass a `REPLICATE_API_KEY`, not an openai key.

**Comment by zajcomm** [comment]
I see.. Honestly I’m not sure why tho. I just clicked on the reply to vercel button on the example GitHub page.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a configuration/support question about using the correct API key for an example deployment, not a confirmed SDK bug or explicit request to change an example.

### Evidence
- The deployment is building the `next-replicate` example, which requires `REPLICATE_API_KEY`, but the reporter supplied an OpenAI API key.
- A maintainer explains that the error originates from the Replicate SDK and identifies the missing credential.
- The reporter primarily asks which authentication value is required and does not establish broken SDK behavior.
