### ISSUE TITLE
Duplicate "Hugging Face" and "HuggingFace" in sidebar nav

### ISSUE THREAD

**Issue by zeke** [vercel-labs/ai#430]
On https://sdk.vercel.ai/docs/guides/providers/hugging-face:

<img width="218" alt="Screenshot 2023-08-08 at 10 31 47 PM" src="https://github.com/vercel-labs/ai/assets/2289/4c7d7822-c250-4f7d-892e-cf1ff9ec3cd2">

**Comment by Matrx123** [comment]
assign #430

**Comment by MaxLeiter** [comment]
Whoops, thanks for the report. Fixed!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This is a correction to the documentation site's sidebar navigation, not a change to AI SDK product behavior.

### Evidence
- The documentation sidebar displayed duplicate provider entries named “Hugging Face” and “HuggingFace.”
- A maintainer acknowledged the documentation navigation error and confirmed it was fixed.
