### ISSUE TITLE
LangChainStream shouldn't close on LLMEnd

### ISSUE THREAD

**Issue by mohamedcherifmo** [vercel-labs/ai#63]
The LangChainStream uses handleLLMEnd instead of handleChainEnd to close the stream, for sequence streams this would cause an issue. 

Below is a sample that gives the following error: 
Error in handler Handler, handleLLMNewToken: TypeError: The stream is closing or closed and cannot be written to

```
const { stream, handlers } = LangChainStream()

  const llm = new ChatOpenAI({
    modelName: "gpt-3.5-turbo", temperature: 0.0,  n: 1,
    streaming: true,
    callbackManager: CallbackManager.fromHandlers(handlers)
  })
  const inquiryChain = new LLMChain({
    llm, prompt: new PromptTemplate({
      template: templates.inquiryTemplate,
      inputVariables: ["prompt", "conversationHistory"],
    }),
    outputKey: "inquiry",

  });
  
  const reviewTemplate = `You are a poem generator, your job is to write a poem about 
  {inquiry}:`;
const reviewPromptTemplate = new PromptTemplate({
  template: reviewTemplate,
  inputVariables: ["inquiry"],
});
const reviewChain = new LLMChain({
  llm: llm,
  prompt: reviewPromptTemplate,
});
  const overallChain = new SequentialChain({
    chains: [inquiryChain, reviewChain],
    inputVariables:["prompt", "conversationHistory"],
    verbose: true,
  });
```

**Comment by jaredpalmer** [comment]
Okay we'll move to `handleChainEnd`!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete failure in existing stream behavior for sequential LangChain chains, with an acknowledged implementation fix.

### Evidence
- LangChainStream closes on `handleLLMEnd`, causing sequential chains to attempt writes after the stream has closed.
- The provided sample produces `TypeError: The stream is closing or closed and cannot be written to`.
- A maintainer confirmed the intended correction: move closure handling to `handleChainEnd`.
