### ISSUE TITLE
Unnecessary div tag in documentation

### ISSUE THREAD

**Issue by eimenhmdt** [vercel-labs/ai#74]
This div tag needs to be removed:

![CleanShot 2023-06-16 at 00 41 18@2x](https://github.com/vercel-labs/ai/assets/64800243/c64df6e1-fb13-429a-8b68-20fb7f631848)

**Comment by jaredpalmer** [comment]
Fixed

**Comment by jaredpalmer** [comment]
Thanks! You rock!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This requests correction of a code snippet in the documentation, without requiring any AI SDK product behavior change.

### Evidence
- The title and description explicitly identify an unnecessary `<div>` in documentation.
- The attached image points to the extraneous tag in a documented code snippet.
- A maintainer confirmed the documentation issue was fixed.
