### ISSUE TITLE
Vue integration

### ISSUE THREAD

**Issue by danielroe** [vercel-labs/ai#77]
I'd be very happy to pitch in to add a Vue integration (and perhaps a Nuxt one too) if you are interested 😊

We could use a utility like https://github.com/Kong/swrv to ensure implementation details are largely similar across libraries.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests new framework support for Vue/Nuxt, which is a product capability expansion.

### Evidence
- The issue proposes adding a new Vue integration, with a possible Nuxt integration as well.
- It does not describe broken or incorrect existing behavior.
